SCREEN_WIDTH = 320
SCREEN_HEIGHT = 240
SCREEN_PIXEL_DIMENSIONS = (SCREEN_WIDTH, SCREEN_HEIGHT)
SCREEN_UPDATE_HERTZ = 60

BLOCK_COUNT = 20
BLOCK_SIZE = int(SCREEN_WIDTH / BLOCK_COUNT)
GRID_OPACITY = 32 # 0-255 Alpha value
ORIGIN = (0, 0)