NAME = 'TETROMANIA'
COPYRIGHT = '(c) MAXIVISION 1985'

SCREEN_WIDTH = 320
SCREEN_HEIGHT = 240
SCREEN_RESOLUTION = (SCREEN_WIDTH, SCREEN_HEIGHT)
SCREEN_REFRESH_RATE = 30
ORIGIN = (0, 0)

FONT_FILENAME = 'font-7x9.png'
FONT_HEIGHT = 9
FONT_WIDTH = 7